import { Footer, Navbar } from "@/Components";
import "./globals.css";
import ThemaProvider from "@/context/ThemaContext";
import AuthProvider from "@/Components/AuthProvider";

export const metadata = {
  title: "App Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/hotspot.ico",
    shortcut: "/hotspot.ico",
    other: {
      rel: "app portfolio",
      url: "/hotspot.ico",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ThemaProvider>
          <AuthProvider>
            <div>
              <div className="container">
                <Navbar />
                {children}
                <Footer />
              </div>
            </div>
          </AuthProvider>
        </ThemaProvider>
      </body>
    </html>
  );
}
