import LayoutContext from "./layoutContect";
export const metadata = {
  title: "App Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/hotspot.ico",
    shortcut: "/hotspot.ico",
    other: {
      rel: "app portfolio",
      url: "/hotspot.ico",
    },
  },
};

export default LayoutContext;
