import { Footer, Navbar } from "@/Components";
import "./globals.css";
import ThemaProvider from "@/context/ThemaContext";
import AuthProvider from "@/Components/AuthProvider";

export const metadata = {
  title: "App Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/hotspot.ico",
    shortcut: "/hotspot.ico",
    other: {
      rel: "app portfolio",
      url: "/hotspot.ico",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="m-0">
          <ThemaProvider>
            <AuthProvider>
              <div>
                  <Navbar />
                  <div className="m-0">{children}</div>
                  <Footer />
              </div>
            </AuthProvider>
          </ThemaProvider>
      </body>
    </html>
  );
}
